args <- commandArgs(trailingOnly = TRUE)
if (!(length(args) == 2)) {
  stop(paste(
    "Incorrect number of arguments!",
    "Usage: Rscript concat_cohort_csvs.R <INPUT FILE LIST> <OUTPUT FILE>",
    "    INPUT FILE LIST:       a text file containing the paths to each final output CSV file generated by the CHIP variant detection pipeline - one file per line and one file per sample.",
    "    OUTPUT FILE:           the path to the output CSV file to be generated.",
    sep = "\n"))
}

all_variants_file <- args[1]
output_file <- args[2]

if (!file.exists(all_variants_file)) {
  stop("Input file does not exist.")
}

inputFiles_csv <- scan(all_variants_file, character())

if (!all(file.exists(inputFiles_csv))) {
  stop("One or more of the input CSV files specified don't exist!")
}

df_all_var_list <- list()
for (i in 1:length(inputFiles_csv)) {
  input_csv <- inputFiles_csv[i]
  df_all_var_list[[i]] <- read.csv(input_csv)
}

# Get column names from first file
cols <- colnames(df_all_var_list[[1]])
# Get column names from second file to compare
cols2 <- colnames(df_all_var_list[[2]])
# Get position of "GENOTYPE" column (should be the only mismatched column name)
genotype_col <- which(cols != cols2)
if (length(genotype_col) != 1) {
  stop("More than one mismatched column name!")
}
# Replace the genotype field name with "GENOTYPE"
cols[genotype_col] <- "GENOTYPE"
# Apply the new column names to all dataframes
for (i in 1:length(df_all_var_list)) {
  colnames(df_all_var_list[[i]]) <- cols
}

# Combine all dataframes into one
df_all_var <- do.call(rbind, df_all_var_list)

# Write to file
write.csv(df_all_var, file = output_file, row.names = FALSE)
