source("./import/update_whitelist.R")

args <- commandArgs(trailingOnly = TRUE)
if (!(length(args) %in% c(1, 2))) {
  stop(paste(
    "Incorrect number of arguments!",
    "Usage: Rscript filter_cohort_chip.R <INPUT FILE LIST> <PREVALENCE THRESHOLD>",
    "    INPUT FILE LIST:       a text file containing the paths to each *.chip_transcript_variants.filtered.putative_filter.csv file generated by the CHIP variant detection pipeline - one file per line.",
    "    PREVALENCE THRESHOLD:  a value between 0 and 1 indicating the maximum desired fraction of samples in which a variant should be present. Default is 0.01 (1%). Variants exceeding this threshold will be flagged for manual review.",
    sep = "\n"))
}

all_variants_file <- args[1]

if (!file.exists(all_variants_file)) {
  stop("Input file does not exist.")
}

max_variant_prevalence <- 0.01
if (length(args) == 2) {
  tmp <- as.numeric(args[2])
  if (tmp >= 0 && tmp <= 1) {
    max_variant_prevalence <- tmp
  } else {
    stop("Invalid prevalence threshold supplied!")
  }
}

inputFiles_csv <- scan(all_variants_file, character())

if (!all(file.exists(inputFiles_csv))) {
  stop("One or more of the input CSV files specified don't exist!")
}

FILTER <- "PASS"  # "ALL", "NO_FAIL", "PASS"

df_all_var_list <- list()
df_all_var_unique_sites_list <- list()
for (i in 1:length(inputFiles_csv)) {
  input_csv <- inputFiles_csv[i]
  df_all_var_list[[i]] <- read.csv(input_csv)
  df_all_var_unique_sites_list[[i]] <- df_all_var_list[[i]][c("Chr", "Start", "End", "Ref", "Alt", "COMBINED_FILTER")]
  # Which variants to consider when determining cohort frequency - all variants, or just those passing the filters
  # Defaults to only considering whitelisted variants
  if (FILTER == "PASS") {
    # Only consider variants that pass the filters
    df_all_var_unique_sites_list[[i]] <- df_all_var_unique_sites_list[[i]][df_all_var_unique_sites_list[[i]]$COMBINED_FILTER == "PASS",]
  } else if (FILTER == "NO_FAIL") {
    # Consider variants that pass the filters, or are marked for manual review
    df_all_var_unique_sites_list[[i]] <- df_all_var_unique_sites_list[[i]][df_all_var_unique_sites_list[[i]]$COMBINED_FILTER != "FAIL",]
  }
  df_all_var_unique_sites_list[[i]] <- unique(df_all_var_unique_sites_list[[i]][c("Chr", "Start", "End", "Ref", "Alt")])
}
df_all_var_unique_sites_count <- do.call(rbind, df_all_var_unique_sites_list)

df_all_var_unique_sites_count$Chr <- as.character(df_all_var_unique_sites_count$Chr)
df_all_var_unique_sites_count$Start <- as.integer(df_all_var_unique_sites_count$Start)
df_all_var_unique_sites_count$End <- as.integer(df_all_var_unique_sites_count$End)
df_all_var_unique_sites_count$Ref <- as.character(df_all_var_unique_sites_count$Ref)
df_all_var_unique_sites_count$Alt <- as.character(df_all_var_unique_sites_count$Alt)

df_all_var_unique <- unique(df_all_var_unique_sites_count)
df_all_var_unique$Chr <- as.character(df_all_var_unique$Chr)
df_all_var_unique$Start <- as.integer(df_all_var_unique$Start)
df_all_var_unique$End <- as.integer(df_all_var_unique$End)
df_all_var_unique$Ref <- as.character(df_all_var_unique$Ref)
df_all_var_unique$Alt <- as.character(df_all_var_unique$Alt)

df_all_var_unique$COUNT <- apply(df_all_var_unique, 1, function(x) {
  CHR <- as.character(x[[1]])
  START <- as.integer(x[[2]])
  END <- as.integer(x[[3]])
  REF <- as.character(x[[4]])
  ALT <- as.character(x[[5]])
  return(sum(
    df_all_var_unique_sites_count$Chr == CHR &
      df_all_var_unique_sites_count$Start == START &
      df_all_var_unique_sites_count$End == END &
      df_all_var_unique_sites_count$Ref == REF &
      df_all_var_unique_sites_count$Alt == ALT
  ))
})
df_all_var_unique$PREVALENCE <- df_all_var_unique$COUNT / length(inputFiles_csv)

df_all_var_unique$PREVALENCE_FILTER <- "PASS"
df_all_var_unique$PREVALENCE_FILTER[df_all_var_unique$PREVALENCE > max_variant_prevalence] <- "FAIL_IF_PUTATIVE"

for (i in 1:length(df_all_var_list)) {
  df_all_var_list[[i]] <- merge(df_all_var_list[[i]], df_all_var_unique, all.x = TRUE)
  df_all_var_list[[i]]$PREVALENCE_FILTER[is.na(df_all_var_list[[i]]$PREVALENCE_FILTER)] <- "FAIL"
  df_all_var_list[[i]]$PREVALENCE_FILTER <- apply(df_all_var_list[[i]][c("PREVALENCE_FILTER", "putative")], 1, function(x) {
    filt <- as.character(x[[1]])
    put = as.logical(x[[2]])
    if (filt == "FAIL") {
      return("FAIL")
    } else if (filt == "PASS") {
      return("PASS")
    } else if (filt == "FAIL_IF_PUTATIVE" && !put) {
      return("PASS")
    } else {
      return("FAIL")
    }
  })
  # Update combined filter
  df_all_var_list[[i]]$COMBINED_FILTER <- apply(df_all_var_list[[i]][c("COMBINED_FILTER", "PREVALENCE_FILTER")], 1, function(x) {
    if (x[[2]] == "PASS") {
      return(x[[1]])
    } else {
      return("FAIL")
    }
  })

  # Write to file
  original_csv_file <- gsub("\\.csv$", "", inputFiles_csv[[i]], perl = TRUE)
  new_csv_file <- paste(original_csv_file, ".cohort_wide_filter.csv", sep = "")
  write.csv(df_all_var_list[[i]], new_csv_file, row.names = FALSE)
}
