args <- commandArgs(trailingOnly = TRUE)
if (!(length(args) %in% c(1, 2))) {
  stop(paste(
    "Incorrect number of arguments!",
    "Usage: Rscript filter_cohort_chip.R <INPUT FILE LIST> <PREVALENCE THRESHOLD>",
    "    INPUT FILE LIST:       a text file containing the paths to each *.all_variants.csv file generated by the CHIP variant detection pipeline - one file per line.",
    "    PREVALENCE THRESHOLD:  a value between 0 and 1 indicating the maximum desired fraction of samples in which a variant should be present. Default is 0.01 (1%). Variants exceeding this threshold will be flagged for manual review.",
    sep = "\n"))
}

all_variants_file <- args[1]

if (!file.exists(all_variants_file)) {
  stop("Input file does not exist.")
}

max_variant_prevalence <- 0.01
if (length(args) == 2) {
  tmp <- as.numeric(args[2])
  if (tmp >= 0 && tmp <= 1) {
    max_variant_prevalence <- tmp
  } else {
    stop("Invalid prevalence threshold supplied!")
  }
}

inputFiles_csv <- scan(all_variants_file, character())

if (!all(file.exists(inputFiles_csv))) {
  stop("One or more of the input CSV files specified don't exist!")
}

df_all_var_list <- list()
df_all_var_combined_list <- list()
for (i in 1:length(inputFiles_csv)) {
  input_csv <- inputFiles_csv[i]
  df_all_var_list[[i]] <- read.csv(input_csv)
  df_all_var_combined_list[[i]] <- df_all_var_list[[i]][c("Chr", "Start", "End", "Ref", "Alt")]
}

df_all_var_combined <- do.call(rbind, df_all_var_combined_list)
df_all_var_combined$Chr <- as.character(df_all_var_combined$Chr)
df_all_var_combined$Start <- as.integer(df_all_var_combined$Start)
df_all_var_combined$End <- as.integer(df_all_var_combined$End)
df_all_var_combined$Ref <- as.character(df_all_var_combined$Ref)
df_all_var_combined$Alt <- as.character(df_all_var_combined$Alt)

df_all_var_unique <- unique(df_all_var_combined)
df_all_var_unique$Chr <- as.character(df_all_var_unique$Chr)
df_all_var_unique$Start <- as.integer(df_all_var_unique$Start)
df_all_var_unique$End <- as.integer(df_all_var_unique$End)
df_all_var_unique$Ref <- as.character(df_all_var_unique$Ref)
df_all_var_unique$Alt <- as.character(df_all_var_unique$Alt)

df_all_var_unique$COUNT <- apply(df_all_var_unique, 1, function(x) {
  CHR <- as.character(x[[1]])
  START <- as.integer(x[[2]])
  END <- as.integer(x[[3]])
  REF <- as.character(x[[4]])
  ALT <- as.character(x[[5]])
  return(sum(
    df_all_var_combined$Chr == CHR &
      df_all_var_combined$Start == START &
      df_all_var_combined$End == END &
      df_all_var_combined$Ref == REF &
      df_all_var_combined$Alt == ALT
  ))
})
df_all_var_unique$PREVALENCE <- df_all_var_unique$COUNT / length(inputFiles_csv)

df_all_var_unique$PREVALENCE_FILTER <- "PASS"
df_all_var_unique$PREVALENCE_FILTER[df_all_var_unique$PREVALENCE > max_variant_prevalence] <- "PASS_IF_KNOWN"

for (i in 1:length(df_all_var_list)) {
  df_all_var_list[[i]] <- merge(df_all_var_list[[i]], df_all_var_unique, all.x = TRUE)
  # Update combined filter
  df_all_var_list[[i]]$COMBINED_FILTER <- apply(df_all_var_list[[i]][c("COMBINED_FILTER", "PREVALENCE_FILTER", "KNOWN")], 1, function(x) {
    known = as.logical(x[[3]])
    if (x[[2]] == "PASS" || known) {
      return(x[[1]])
    } else {
      return("FAIL")
    }
  })
  # Update whitelist
  df_all_var_list[[i]]$Whitelist <- as.logical(df_all_var_list[[i]]$Whitelist)
  df_all_var_list[[i]]$Putative_Whitelist <- as.logical(df_all_var_list[[i]]$Putative_Whitelist)
  df_all_var_list[[i]]$Manual_Review <- as.logical(df_all_var_list[[i]]$Manual_Review)
  df_all_var_list[[i]]$Putative_Manual_Review <- as.logical(df_all_var_list[[i]]$Putative_Manual_Review)

  df_all_var_list[[i]]$Manual_Review <- (df_all_var_list[[i]]$Manual_Review & df_all_var_list[[i]]$COMBINED_FILTER != "FAIL") | (df_all_var_list[[i]]$Whitelist & df_all_var_list[[i]]$COMBINED_FILTER == "MANUAL_REVIEW")
  df_all_var_list[[i]]$Whitelist <- df_all_var_list[[i]]$Whitelist & df_all_var_list[[i]]$COMBINED_FILTER == "PASS"
  df_all_var_list[[i]]$Putative_Manual_Review <- (df_all_var_list[[i]]$Putative_Manual_Review & df_all_var_list[[i]]$COMBINED_FILTER != "FAIL") | (df_all_var_list[[i]]$Putative_Whitelist & df_all_var_list[[i]]$COMBINED_FILTER == "MANUAL_REVIEW")
  df_all_var_list[[i]]$Putative_Whitelist <- df_all_var_list[[i]]$Putative_Whitelist & df_all_var_list[[i]]$COMBINED_FILTER == "PASS"
  # Write to file
  new_csv_file <- paste(inputFiles_csv[[i]], ".cohort_wide_filter.all_variants.csv", sep = "")
  write.csv(df_all_var_list[[i]], new_csv_file, row.names = FALSE)
  new_csv_file <- paste(inputFiles_csv[[i]], ".cohort_wide_filter.chip_wl_variants.csv", sep = "")
  write.csv(df_all_var_list[[i]][df_all_var_list[[i]]$Whitelist,], new_csv_file, row.names = FALSE)
  new_csv_file <- paste(inputFiles_csv[[i]], ".cohort_wide_filter.chip_putative_wl_variants.csv", sep = "")
  write.csv(df_all_var_list[[i]][df_all_var_list[[i]]$Putative_Whitelist,], new_csv_file, row.names = FALSE)
  new_csv_file <- paste(inputFiles_csv[[i]], ".cohort_wide_filter.chip_manual_review_variants.csv", sep = "")
  write.csv(df_all_var_list[[i]][df_all_var_list[[i]]$Manual_Review,], new_csv_file, row.names = FALSE)
  new_csv_file <- paste(inputFiles_csv[[i]], ".cohort_wide_filter.chip_putative_manual_review_variants.csv", sep = "")
  write.csv(df_all_var_list[[i]][df_all_var_list[[i]]$Putative_Manual_Review,], new_csv_file, row.names = FALSE)
}
