version: 1.2
workflows:
  - name: KCCGMutect2CHIP
    subclass: WDL
    primaryDescriptorPath: /workflow/full.wdl
    publish: true
    authors:
      - name: "Michael Geaghan"
        orcid: "0000-0002-4350-8600"
        email: m.geaghan@garvan.org.au
        role: "Production Bioinformatician"
        affiliation: "Garvan Institute of Medical Research"
  - name: KCCGMutect2CHIP_M2
    subclass: WDL
    primaryDescriptorPath: /workflow/m2.wdl
    publish: true
    authors:
      - name: "Michael Geaghan"
        orcid: "0000-0002-4350-8600"
        email: m.geaghan@garvan.org.au
        role: "Production Bioinformatician"
        affiliation: "Garvan Institute of Medical Research"
  - name: KCCGMutect2CHIP_VEP
    subclass: WDL
    primaryDescriptorPath: /workflow/vep.wdl
    publish: true
    authors:
      - name: "Michael Geaghan"
        orcid: "0000-0002-4350-8600"
        email: m.geaghan@garvan.org.au
        role: "Production Bioinformatician"
        affiliation: "Garvan Institute of Medical Research"
  - name: KCCGMutect2CHIP_Annovar
    subclass: WDL
    primaryDescriptorPath: /workflow/annovar.wdl
    publish: true
    authors:
      - name: "Michael Geaghan"
        orcid: "0000-0002-4350-8600"
        email: m.geaghan@garvan.org.au
        role: "Production Bioinformatician"
        affiliation: "Garvan Institute of Medical Research"
  - name: KCCGMutect2CHIP_SpliceAI
    subclass: WDL
    primaryDescriptorPath: /workflow/spliceai.wdl
    publish: true
    authors:
      - name: "Michael Geaghan"
        orcid: "0000-0002-4350-8600"
        email: m.geaghan@garvan.org.au
        role: "Production Bioinformatician"
        affiliation: "Garvan Institute of Medical Research"
  - name: KCCGMutect2CHIP_CHIP
    subclass: WDL
    primaryDescriptorPath: /workflow/chip.wdl
    publish: true
    authors:
      - name: "Michael Geaghan"
        orcid: "0000-0002-4350-8600"
        email: m.geaghan@garvan.org.au
        role: "Production Bioinformatician"
        affiliation: "Garvan Institute of Medical Research"
  - name: KCCGMutect2CHIP_PoN
    subclass: WDL
    primaryDescriptorPath: /workflow/pon.wdl
    publish: true
    authors:
      - name: "Michael Geaghan"
        orcid: "0000-0002-4350-8600"
        email: m.geaghan@garvan.org.au
        role: "Production Bioinformatician"
        affiliation: "Garvan Institute of Medical Research"
  - name: KCCGMutect2CHIP_Annotate_Cohort
    subclass: WDL
    primaryDescriptorPath: /workflow/annotate_cohort.wdl
    publish: true
    authors:
      - name: "Michael Geaghan"
        orcid: "0000-0002-4350-8600"
        email: m.geaghan@garvan.org.au
        role: "Production Bioinformatician"
        affiliation: "Garvan Institute of Medical Research"
  - name: KCCGMutect2CHIP_CHIP_Cohort
    subclass: WDL
    primaryDescriptorPath: /workflow/chip_cohort.wdl
    publish: true
    authors:
      - name: "Michael Geaghan"
        orcid: "0000-0002-4350-8600"
        email: m.geaghan@garvan.org.au
        role: "Production Bioinformatician"
        affiliation: "Garvan Institute of Medical Research"
