[workflow]
dataset = ''
access_level = 'test'
name = 'TEST_RUN'

[mutect2_chip]
intervals = 'OPTIONAL_FILE'
ref_fasta = 'REQUIRED_FILE'
ref_fai = 'REQUIRED_FILE'
ref_dict = 'REQUIRED_FILE'
tumor_reads = 'REQUIRED_FILE'
tumor_reads_index = 'REQUIRED_FILE'
normal_reads = 'OPTIONAL_FILE'
normal_reads_index = 'OPTIONAL_FILE'
pon = 'OPTIONAL_FILE'
pon_idx = 'OPTIONAL_FILE'
scatter_count = 10
gnomad = 'OPTIONAL_FILE'
gnomad_idx = 'OPTIONAL_FILE'
variants_for_contamination = 'OPTIONAL_FILE'
variants_for_contamination_idx = 'OPTIONAL_FILE'
run_orientation_bias_mixture_model_filter = true
m2_extra_args = '--pcr-indel-model NONE --downsampling-stride 20 --max-reads-per-alignment-start 6 --max-suspicious-reads-per-alignment-start 6'
m2_extra_filtering_args = 'OPTIONAL_STRING'
split_intervals_extra_args = 'OPTIONAL_STRING'
make_bamout = true
compress_vcfs = true
gga_vcf = 'OPTIONAL_FILE'
gga_vcf_idx = 'OPTIONAL_FILE'
gatk_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/gatk@sha256:0359ae4f32f2f541ca86a8cd30ef730bbaf8c306b9d53d2d520262d3e84b3b2b'
gatk_override = 'OPTIONAL_FILE'
preemptible = 2
max_retries = 2
small_task_cpu = 4
small_task_mem = 4000
small_task_disk = 100
command_mem_padding = 1000
boot_disk_size = 12
m2_mem = 5000
m2_cpu = 4
learn_read_orientation_mem = 5000
filter_alignment_artifacts_mem = 5000
emergency_extra_disk = 0
large_input_to_output_multiplier = 2.25
small_input_to_output_multiplier = 2.0
