[workflow]
dataset = ''
access_level = 'test'
name = 'TEST_RUN'

[mutect2_chip]
Mutect2.intervals = 'OPTIONAL_FILE'
Mutect2.ref_fasta = 'REQUIRED_FILE'
Mutect2.ref_fai = 'REQUIRED_FILE'
Mutect2.ref_dict = 'REQUIRED_FILE'
Mutect2.tumor_bam = 'REQUIRED_FILE'
Mutect2.tumor_bai = 'REQUIRED_FILE'
Mutect2.normal_bam = 'OPTIONAL_FILE'
Mutect2.normal_bai = 'OPTIONAL_FILE'
Mutect2.pon = 'OPTIONAL_FILE'
Mutect2.pon_idx = 'OPTIONAL_FILE'
Mutect2.gnomad = 'OPTIONAL_FILE'
Mutect2.gnomad_idx = 'OPTIONAL_FILE'
Mutect2.variants_for_contamination = 'OPTIONAL_FILE'
Mutect2.variants_for_contamination_idx = 'OPTIONAL_FILE'
Mutect2.m2_extra_args = '--pcr-indel-model NONE --downsampling-stride 20 --max-reads-per-alignment-start 6 --max-suspicious-reads-per-alignment-start 6'
Mutect2.m2_extra_filtering_args = 'OPTIONAL_STRING'
Mutect2.make_bamout = true
Mutect2.compress = true
Mutect2.gga_vcf = 'OPTIONAL_FILE'
Mutect2.gga_vcf_idx = 'OPTIONAL_FILE'
Mutect2.gatk_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/gatk@sha256:0359ae4f32f2f541ca86a8cd30ef730bbaf8c306b9d53d2d520262d3e84b3b2b'
Mutect2.gatk_override = 'OPTIONAL_FILE'
Mutect2.preemptible = 2
Mutect2.max_retries = 2
Mutect2.boot_disk_size = 12
Mutect2.cpu = 4
Mutect2.mem_mb = 5000
Mutect2.disk_space = 100
Mutect2.command_mem_padding = 1000
Mutect2.emergency_extra_disk = 0