[workflow]
dataset = ''
access_level = 'test'
name = 'TEST_RUN'

[mutect2_chip]
intervals = 'REQUIRED_FILE'
ref_fasta = 'REQUIRED_FILE'
ref_fai = 'REQUIRED_FILE'
ref_dict = 'REQUIRED_FILE'
tumor_reads = 'REQUIRED_FILE'
tumor_reads_index = 'REQUIRED_FILE'
normal_reads = 'OPTIONAL_FILE'
normal_reads_index = 'OPTIONAL_FILE'
pon = 'OPTIONAL_FILE'
pon_idx = 'OPTIONAL_FILE'
scatter_count = 10
gnomad = 'OPTIONAL_FILE'
gnomad_idx = 'OPTIONAL_FILE'
variants_for_contamination = 'OPTIONAL_FILE'
variants_for_contamination_idx = 'OPTIONAL_FILE'
run_orientation_bias_mixture_model_filter = true
m2_extra_args = '--pcr-indel-model NONE --downsampling-stride 20 --max-reads-per-alignment-start 6 --max-suspicious-reads-per-alignment-start 6'
m2_extra_filtering_args = 'OPTIONAL_STRING'
split_intervals_extra_args = 'OPTIONAL_STRING'
make_bamout = true
compress_vcfs = true
gga_vcf = 'OPTIONAL_FILE'
gga_vcf_idx = 'OPTIONAL_FILE'
vep = true
vep_cache_archive = 'OPTIONAL_ZIP_FILE'
vep_species = 'homo_sapiens'
vep_assembly = 'GRCh38'
vep_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/vep@sha256:bc6a74bf271adb1484ea769660c7b69f5eea033d3ba2e2947988e6c5f034f221'
loftee = true
vep_loftee_ancestor_fa = 'OPTIONAL_FILE'
vep_loftee_ancestor_fai = 'OPTIONAL_FILE'
vep_loftee_ancestor_gzi = 'OPTIONAL_FILE'
vep_loftee_conservation_sql = 'OPTIONAL_FILE'
loftee_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/vep-loftee@sha256:c95b78bacef4c8d3770642138e6f28998a5034cfad3fbef5451d2303c8c795d3'
annovar = false
annovar_archive = 'OPTIONAL_ZIP_FILE'
annovar_assembly = 'hg38'
annovar_protocols = 'cosmic95_coding,cosmic95_noncoding,dbnsfp42a,clinvar_20221231,gnomad211_exome,refGene'
annovar_operations = 'f,f,f,f,f,g'
annovar_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/perl@sha256:1f35086e2ff48dace3b3edeaa2ad1faf1e44c0612e00f00ea0fc1830b576a261'
spliceai = false
spliceai_annotation_file = 'OPTIONAL_FILE'
spliceai_annotation_string = 'grch38'
spliceai_max_dist = 50
spliceai_mask = false
spliceai_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/spliceai@sha256:617682496a3f475c69ccdfe593156b79dd1ba21e02481ed1d0d8b740f3422530'
run_chip_detection = true
treat_missing_as_rare = true
whitelist_genome = true
whitelist_use_ensembl_annotation = false
run_chip_on_unannotated_vcf = false
gnomad_pop = 'AF'
whitelist_filter_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/whitelist_filter@sha256:9cd77186c23a0b256a0928c5a4087b8378c234cb0754f35557cf9ec6d4aa544d'
samtools_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/vep-loftee@sha256:c95b78bacef4c8d3770642138e6f28998a5034cfad3fbef5451d2303c8c795d3'
gatk_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/gatk@sha256:0359ae4f32f2f541ca86a8cd30ef730bbaf8c306b9d53d2d520262d3e84b3b2b'
gatk_override = 'OPTIONAL_FILE'
preemptible = 2
max_retries = 2
small_task_cpu = 4
small_task_mem = 4000
small_task_disk = 100
command_mem_padding = 1000
boot_disk_size = 12
m2_mem = 5000
m2_cpu = 4
learn_read_orientation_mem = 5000
filter_alignment_artifacts_mem = 5000
vep_mem = 32000
vep_cpu = 1
vep_tmp_disk = 100
annovar_mem_mb = 4000
annovar_disk = 100
annovar_tmp_disk = 200
spliceai_disk = 100
spliceai_mem_mb = 16000
spliceai_cpu = 4
whitelist_mem_mb = 10000
whitelist_disk = 300
emergency_extra_disk = 0
large_input_to_output_multiplier = 2.25
small_input_to_output_multiplier = 2.0
