[workflow]
dataset = ''
access_level = 'test'
name = 'TEST_RUN'

[mutect2_chip]
intervals = 'OPTIONAL_FILE'
ref_fasta = 'REQUIRED_FILE'
ref_fai = 'REQUIRED_FILE'
ref_dict = 'REQUIRED_FILE'
tumor_bam = 'REQUIRED_FILE'
tumor_bai = 'REQUIRED_FILE'
normal_bam = 'OPTIONAL_FILE'
normal_bai = 'OPTIONAL_FILE'
pon = 'OPTIONAL_FILE'
pon_idx = 'OPTIONAL_FILE'
gnomad = 'OPTIONAL_FILE'
gnomad_idx = 'OPTIONAL_FILE'
variants_for_contamination = 'OPTIONAL_FILE'
variants_for_contamination_idx = 'OPTIONAL_FILE'
m2_extra_args = '--pcr-indel-model NONE --downsampling-stride 20 --max-reads-per-alignment-start 6 --max-suspicious-reads-per-alignment-start 6'
m2_extra_filtering_args = 'OPTIONAL_STRING'
make_bamout = true
compress = true
gga_vcf = 'OPTIONAL_FILE'
gga_vcf_idx = 'OPTIONAL_FILE'
gatk_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/gatk@sha256:0359ae4f32f2f541ca86a8cd30ef730bbaf8c306b9d53d2d520262d3e84b3b2b'
gatk_override = 'OPTIONAL_FILE'
preemptible = 2
max_retries = 2
boot_disk_size = 12
cpu = 4
mem_mb = 5000
disk_space = 100
command_mem_padding = 1000
emergency_extra_disk = 0